services:
  - type: web
    name: jikan-api
    env: docker
    plan: free
    region: singapore
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_TIMEZONE
        value: UTC
      - key: APP_DEPRECATION
        value: false
      - key: APP_BROWNOUT
        value: false
      - key: CACHE_DRIVER
        value: mongodb
      - key: CACHE_METHOD
        value: legacy
      - key: CACHE_DEFAULT_EXPIRE
        value: 86400
      - key: CACHE_META_EXPIRE
        value: 300
      - key: CACHE_USER_EXPIRE
        value: 300
      - key: CACHE_404_EXPIRE
        value: 604800
      - key: CACHE_SEARCH_EXPIRE
        value: 432000
      - key: MICROCACHING
        value: false
      - key: THROTTLE
        value: false
      - key: MONGODB_URI
        value: mongodb+srv://jikan_user:JikanDeploy2024!secure@aniocean.y930vxk.mongodb.net/jikan?retryWrites=true&w=majority&appName=Aniocean
      - key: MONGODB_DATABASE
        value: jikan
      - key: MONGODB_CACHE_COLLECTION
        value: cache
      - key: GITHUB_REPORTING
        value: false